In [1]:
# Assignment 1
import csv
%precision 2
with open("mpg.csv") as csvFile:
    mpg = list(csv.DictReader(csvFile))

In [2]:
mpg

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'},
 {'': '4',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'auto(av)',
  'drv': 'f',
  'cty': '21',
  'hwy': '30',
  'fl': 'p',
  'class': 'compact'},
 {'': '5',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2.8',
  'year': '1999',
  'cyl': '6',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '16',
  'hwy': '26',
 

In [3]:
mpg[:3]

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [4]:
len(mpg)

234

In [5]:
# Column names
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [6]:
sum_ = 0
c = 1
for d in mpg:
    if d["cty"]:
        sum_ += float(d["cty"])
        c += 1
print(sum_/c)

16.78723404255319


In [7]:
sum_ = 0
c = 0
for d in mpg:
    if d["hwy"]:
        sum_ += float(d["hwy"])
        c += 1
print(sum_/c)

23.44017094017094


In [8]:
cyl_u = set(d["cyl"] for d in mpg)
print(cyl_u)

{'8', '5', '4', '6'}


In [9]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass
lst = []
for veh in vehicleclass:
    sum_ = 0
    c = 0
    for each_ in mpg:
        if veh == each_["class"]:
            sum_ += float(each_["hwy"])
            c += 1
    lst.append((veh,sum_/c))
print(lst)

[('minivan', 22.363636363636363), ('suv', 18.129032258064516), ('midsize', 27.29268292682927), ('2seater', 24.8), ('subcompact', 28.142857142857142), ('compact', 28.29787234042553), ('pickup', 16.87878787878788)]


In [10]:
import datetime as dt
import time as tm
tm.time()

1684069833.35

In [11]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2023, 5, 14, 9, 10, 33, 348900)

In [12]:
dtnow.year

2023

In [13]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [14]:
today = dt.date.today()
today

datetime.date(2023, 5, 14)

In [15]:
today.year


2023

In [16]:
a = map(sum,[1,2,3],[3,4,5])

In [17]:
fn = lambda a, b ,c: a+b

In [18]:
fn(2,3,4)

5

In [19]:
import numpy as np

In [20]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.array([1,2,3])

array([1, 2, 3])

In [23]:
arr = np.array([[2,3,4],[5,6,7]])

In [24]:
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [25]:
arr.reshape(3,2)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [26]:
arr.shape

(2, 3)

In [27]:
arr = np.arange(2,15,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14])

In [28]:
arr2 = np.linspace(2,15,3)
arr2

array([ 2. ,  8.5, 15. ])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.diag(arr2)

array([[ 2. ,  0. ,  0. ],
       [ 0. ,  8.5,  0. ],
       [ 0. ,  0. , 15. ]])

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
type(a),a.dtype


(numpy.ndarray, dtype('int64'))

In [34]:
a.astype("f")

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [35]:
a.argmax() # Returns index

5

In [36]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
myarr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [38]:
# get data as a gentextfromcsv in an array
arr_ = np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=1)
arr_

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [39]:
# Regular expression
import re
txt = "ameya is hardworking,ameya gets good grades, ameya is smart"
# re.findall("[a-zA-Z]",txt)
re.findall("ameya.*",txt)

['ameya is hardworking,ameya gets good grades, ameya is smart']

In [40]:
re.split("ameya",txt)

['', ' is hardworking,', ' gets good grades, ', ' is smart']

In [41]:
grades = "ACBAAABCBAABAA"
# re.findall("A",grades)
re.findall("[A][B-C]",grades)

['AC', 'AB', 'AB']

In [42]:
re.findall("[^A]",grades)

['C', 'B', 'B', 'C', 'B', 'B']

In [43]:
re.findall("A{1,10}B{1,10}C{1,2}",grades)

['AAABC']

In [44]:
with open("ferpa.txt") as file:
    wiki = file.read()
# re.findall(,grades)
wiki

'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [45]:
# re.findall("[a-zA-Z]{1,100}.*\[edit\]",wiki)
re.findall("[\w]{1,100}.*\[edit\]",wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [46]:
re.findall("[\w].*\[edit\]",wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [47]:
for i in re.findall("[\w].*\[edit\]",wiki):
    print(re.split("[\[]",i)[0])

Overview
Access to public records
Student medical records


In [48]:
for i in re.finditer("([\w].*)(\[edit\])",wiki):
    print(i.group(1))

Overview
Access to public records
Student medical records


In [49]:
for i in re.finditer("(?P<title>[\w].*)(?P<edit_tag>\[edit\])",wiki):
    print(i.groupdict()["title"])

Overview
Access to public records
Student medical records


In [50]:
for i in re.finditer("(?P<title>[\w].*)(?=\[edit\])",wiki):
    print(i)

<re.Match object; span=(0, 8), match='Overview'>
<re.Match object; span=(2715, 2739), match='Access to public records'>
<re.Match object; span=(3692, 3715), match='Student medical records'>


In [51]:
# Pandas
import pandas as pd
# Nan when missing value in a number, None when missing value is in strings
nums = [1,2,3,None]
pd.Series(nums)


0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [52]:
nums = ["a","b",None]
pd.Series(nums)

0       a
1       b
2    None
dtype: object

In [53]:
nums = [{"k1":"v1","k2":"v2"}]
pd.Series(nums)

0    {'k1': 'v1', 'k2': 'v2'}
dtype: object

In [54]:
nums = [(1,"v1"),(2,"v2")]
pd.Series(nums,index=["2","3"])

2    (1, v1)
3    (2, v2)
dtype: object

In [56]:
#iloc and number [] same as loc and [""]
# Data frame is a combinations where each row is. a series
# For a series np.sum and all can be used

purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [58]:
df.loc["Store 1"]

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [59]:
df.iloc[1]

Name                     Kevyn
Item Purchased    Kitty Litter
Cost                       2.5
Name: Store 1, dtype: object

In [62]:
# loc and iloc were used for querying a particular row
df.T.iloc[1]

Store 1        Dog Food
Store 1    Kitty Litter
Store 2       Bird Seed
Name: Item Purchased, dtype: object

In [65]:
df["Name"] # Directly use keys for getting the columns

Store 1    Chris
Store 1    Kevyn
Store 2    Vinod
Name: Name, dtype: object

In [69]:
df.iloc[:,2]

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [71]:
df.loc[:,["Cost","Name"]]

Cost   Name
Store 1  22.5  Chris
Store 1   2.5  Kevyn
Store 2   5.0  Vinod

In [72]:
df.iloc[:,[0,2]]

Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0